// Code generated by goctl. DO NOT EDIT.
// Source: userrpc.rpc

package server

import (
	"context"

	"test/userrpc/internal/logic"
	"test/userrpc/internal/svc"
	"test/userrpc/userrpc"
)

type UserrpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserrpcServer
}

func NewUserrpcServer(svcCtx *svc.ServiceContext) *UserrpcServer {
	return &UserrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserrpcServer) Login(ctx context.Context, in *userrpc.Login) (*userrpc.StreamResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserrpcServer) Register(ctx context.Context, in *userrpc.UserRegister) (*userrpc.StreamResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
