// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: userrpc.rpc

package userrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Userrpc_Login_FullMethodName    = "/userrpc.Userrpc/login"
	Userrpc_Register_FullMethodName = "/userrpc.Userrpc/Register"
)

// UserrpcClient is the config API for Userrpc service.yaml.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserrpcClient interface {
	Login(ctx context.Context, in *Login, opts ...grpc.CallOption) (*StreamResp, error)
	Register(ctx context.Context, in *UserRegister, opts ...grpc.CallOption) (*StreamResp, error)
}

type userrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserrpcClient(cc grpc.ClientConnInterface) UserrpcClient {
	return &userrpcClient{cc}
}

func (c *userrpcClient) Login(ctx context.Context, in *Login, opts ...grpc.CallOption) (*StreamResp, error) {
	out := new(StreamResp)
	err := c.cc.Invoke(ctx, Userrpc_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) Register(ctx context.Context, in *UserRegister, opts ...grpc.CallOption) (*StreamResp, error) {
	out := new(StreamResp)
	err := c.cc.Invoke(ctx, Userrpc_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserrpcServer is the server API for Userrpc service.yaml.
// All implementations must embed UnimplementedUserrpcServer
// for forward compatibility
type UserrpcServer interface {
	Login(context.Context, *Login) (*StreamResp, error)
	Register(context.Context, *UserRegister) (*StreamResp, error)
	mustEmbedUnimplementedUserrpcServer()
}

// UnimplementedUserrpcServer must be embedded to have forward compatible implementations.
type UnimplementedUserrpcServer struct {
}

func (UnimplementedUserrpcServer) Login(context.Context, *Login) (*StreamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserrpcServer) Register(context.Context, *UserRegister) (*StreamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserrpcServer) mustEmbedUnimplementedUserrpcServer() {}

// UnsafeUserrpcServer may be embedded to opt out of forward compatibility for this service.yaml.
// Use of this interface is not recommended, as added methods to UserrpcServer will
// result in compilation errors.
type UnsafeUserrpcServer interface {
	mustEmbedUnimplementedUserrpcServer()
}

func RegisterUserrpcServer(s grpc.ServiceRegistrar, srv UserrpcServer) {
	s.RegisterService(&Userrpc_ServiceDesc, srv)
}

func _Userrpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Login)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).Login(ctx, req.(*Login))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).Register(ctx, req.(*UserRegister))
	}
	return interceptor(ctx, in, info, handler)
}

// Userrpc_ServiceDesc is the grpc.ServiceDesc for Userrpc service.yaml.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userrpc.Userrpc",
	HandlerType: (*UserrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _Userrpc_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Userrpc_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userrpc.rpc",
}
