apiVersion: v1
kind: Service
metadata:
  name: user-rpc-service
spec:
  selector:
    app: user-rpc  # 选择具有app: my-go-app标签的Pod
  ports:
    - protocol: TCP
      port: 80  # Service暴露的端口
      targetPort: 8882  # Pod中容器的端口
  type: NodePort  # 将Service暴露为NodePort类型